/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package YahtzeeBot.app.game;

import java.util.Scanner;

import YahtzeeBot.app.bot.Expect;

import java.util.*;
import java.lang.*;
import java.io.*;

public class App {
    public static void main(String[] args) {
        Scanner scnr = new Scanner(System.in);
        System.out.println("Enter number of players:");
        int playerCount = Integer.valueOf(scnr.nextLine());
        int turnNum = 0;

        Player[] players = new Player[playerCount];
        int playerNum = 0;
        for (int i = 0; i < players.length; i++) {
            players[i] = new Player(++playerNum);
        }

        Expect e = new Expect();

        while (turnNum < 13) {
            turnNum++;
            System.out.println("Turn number " + turnNum);
            for(Player p : players){
                Roll roll = new Roll();
                for(int i = 0; i < 2; i ++){
                    roll.roll();
                    System.out.println("\nRoll " + ( i + 1) );
                    e.getExpect(roll, i+1);
                    Printer.printRoll(roll);
                    
                    game.getRollInput(roll, p, i+1, scnr);
                }   
                System.out.println("Roll 3");
                roll.roll();
                Printer.printRoll(roll);
                int input = game.getOptionInput(p, scnr, roll);
                
                int points = game.getPoints(roll, input);
                game.assignPoints(input, p, points);
                Printer.printScore(p);
            }
            

        }

    }
}
