/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package YahtzeeBot.app;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner scnr = new Scanner(System.in);
        System.out.println("Enter number of players:");
        int playerCount = scnr.nextInt();
        int turnNum = 0;

        Player[] players = new Player[playerCount];
        int playerNum = 0;
        for (Player p : players) {
            p = new Player(++playerNum);
        }

        Die[] roll = new Die[5];
        while (turnNum < 13) {
            for(Player p : players){
                turnNum++;
                System.out.println("Turn number " + turnNum);
                game.getRoll(roll);
                

            }
            

        }

    }
}
